### ISSUE TITLE
Nuevas ideas

### ISSUE THREAD

**Issue by Zaikonurami** [KitsuneCode/animaction#1]
Ayuda xdxd

**Comment by Hanako-commands** [comment]
Con que te ayudo queria Kitsu Bv

**Comment by Zaikonurami** [comment]
Dame ideas

**Comment by Zaikonurami** [comment]
Porfa xd

**Comment by Hanako-commands** [comment]
pues u.u

**Comment by Hanako-commands** [comment]
ideas de comandos verdad?

**Comment by Zaikonurami** [comment]
si, las acciones y eso

**Comment by Hanako-commands** [comment]
aa ok

**Comment by Hanako-commands** [comment]
decime que acciones tiene KoNeko o activala y te ayudo sjjsjsj

**Comment by Zaikonurami** [comment]
Puedes ver las que estan en la [carpeta functions](https://github.com/KitsuneCode/animaction/tree/main/functions)

**Comment by Zaikonurami** [comment]
jsjs

**Comment by Hanako-commands** [comment]
ok Bv
